[server]
host = "localhost"
port = "8080"
timeout = "120s"

[storage]
db_connection_string = "postgres://postgres:123@localhost:5432/bannerrotation?sslmode=disable"

[log]
file = "rotator.log"
level = "trace"